builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/twitchdl/main.go
    binary: twitchdl
    ldflags: -X main.defaultClientID=kimne78kx3ncx6brgo4mv6wki5h1ko
archives:
  - id: "archives"
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
env_files:
  github_token: ./github_token
